### ISSUE TITLE
When will the codes be available

### ISSUE THREAD

**Issue by MemoriesJ** [kleinzcy/MIKT-NCD#1]
Hi Klein,

I noticed your work from the Openview, which is very interesting.
I am wondering when the codes will be available since there are some implementation details I cannot wait to know.

Thank you

**Comment by kleinzcy** [comment]
Hi, @MemoriesJ 

Thanks for your attention.

The code will be available after our paper are accepted by a conference. We will notice you when we opensource our code. 

Klein.

**Comment by kleinzcy** [comment]
Hi, @MemoriesJ 

The derivation of MI in manuscript is wrong. So you can ignore our manuscript.

klein
